/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { Ref, useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { ReactThreeFiber } from 'react-three-fiber';
import THREE, { Euler } from 'three';


export function Mars(props: ReactThreeFiber.Object3DNode<THREE.Group, typeof THREE.Group>) {
  const gltf = useGLTF('/images/mars.glb');

  return (
    <primitive object={gltf.scene}  {...props} />
  )
}

useGLTF.preload('/images/mars.glb')
